src/Entity/Employers.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EmployersRepository")
 */
class Employers
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="integer")
     */
    private $company_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getCompanyId(): ?int
    {
        return $this->company_id;
    }

    public function setCompanyId(int $company_id): self
    {
        $this->company_id = $company_id;

        return $this;
    }
}

src/Form/EmployersType.php
<?php

namespace App\Form;

use App\Entity\Employers;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EmployersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('first_name')
            ->add('last_name')
            ->add('email')
            ->add('phone')
            ->add('company_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Employers::class,
        ]);
    }
}

src/Controller/EmployersController.php
<?php

namespace App\Controller;

use App\Entity\Employers;
use App\Form\EmployersType;
use App\Repository\EmployersRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/")
 */
class EmployersController extends AbstractController
{
    /**
     * @Route("/", name="employers_index", methods={"GET"})
     */
    public function index(EmployersRepository $employersRepository): Response
    {
        return $this->render('employers/index.html.twig', [
            'employers' => $employersRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="employers_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $employer = new Employers();
        $form = $this->createForm(EmployersType::class, $employer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($employer);
            $entityManager->flush();

            return $this->redirectToRoute('employers_index');
        }

        return $this->render('employers/new.html.twig', [
            'employer' => $employer,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="employers_show", methods={"GET"})
     */
    public function show(Employers $employer): Response
    {
        return $this->render('employers/show.html.twig', [
            'employer' => $employer,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="employers_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Employers $employer): Response
    {
        $form = $this->createForm(EmployersType::class, $employer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('employers_index');
        }

        return $this->render('employers/edit.html.twig', [
            'employer' => $employer,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="employers_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Employers $employer): Response
    {
        if ($this->isCsrfTokenValid('delete'.$employer->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($employer);
            $entityManager->flush();
        }

        return $this->redirectToRoute('employers_index');
    }
}

templates/employers/_delete_form.html.twig
<form method="post" action="{{ path('employers_delete', {'id': employer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ employer.id) }}">
    <button class="btn btn-md btn-danger">Delete</button>
</form>

templates/employers/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button  class="btn btn-md btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/employers/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Employers{% endblock %}

{% block body %}
    <div class="container">
    <h1>Edit Employers</h1>


    {{ include('employers/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-md btn-warning" {{ path('employers_index') }}">back to list</a>

    {{ include('employers/_delete_form.html.twig') }}

    </div>
{% endblock %}

templates/employers/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Employers index{% endblock %}

{% block body %}
    <div class="container mt-5">

    <h1>Employers index</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>First_name</th>
                <th>Last_name</th>
                <th>Email</th>
                <th>Phone</th>
{#                <th>Company_id</th>#}
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for employer in employers %}
            <tr>
                <td>{{ employer.id }}</td>
                <td>{{ employer.firstName }}</td>
                <td>{{ employer.lastName }}</td>
                <td>{{ employer.email }}</td>
                <td>{{ employer.phone }}</td>
{#                <td>{{ employer.companyId }}</td>#}
                <td>
                    <a class="btn btn-md btn-warning" href="{{ path('employers_show', {'id': employer.id}) }}">show</a>
                    <a class="btn btn-md btn-warning" href="{{ path('employers_edit', {'id': employer.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-md btn-success" href="{{ path('employers_new') }}">Create new</a>
</div>
{% endblock %}

templates/employers/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Employers{% endblock %}

{% block body %}
    <div class="container">
    <h1>Create new Employers</h1>

    {{ include('employers/_form.html.twig') }}

    <a class="btn btn-md btn-" href="{{ path('employers_index') }}">back to list</a>
    </div>
{% endblock %}

templates/employers/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Employers{% endblock %}

{% block body %}
    <div class="container mt-5">
    <h1>Employers</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ employer.id }}</td>
            </tr>
            <tr>
                <th>First_name</th>
                <td>{{ employer.firstName }}</td>
            </tr>
            <tr>
                <th>Last_name</th>
                <td>{{ employer.lastName }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ employer.email }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ employer.phone }}</td>
            </tr>
            <tr>
                <th>Company_id</th>
                <td>{{ employer.companyId }}</td>
            </tr>
        </tbody>
    </table>
    <div class="inline" style="display: flex; justify-content: space-between;">
    <a class="btn btn-md btn-warning" href="{{ path('employers_index') }}">back to list</a>

    <a class="btn btn-md btn-warning" href="{{ path('employers_edit', {'id': employer.id}) }}">edit</a>

    {{ include('employers/_delete_form.html.twig') }}
    </div>
    </div>
{% endblock %}